# Generated by Django 5.0.6 on 2026-02-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plan_name',
            field=models.CharField(default='Private Cloud', max_length=60),
        ),
        migrations.AddField(
            model_name='account',
            name='security_profile',
            field=models.CharField(default='256-bit AES', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='storage_quota_gb',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=64)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('team', 'Team share'), ('public', 'Public link')], default='private', max_length=16)),
                ('status', models.CharField(choices=[('synced', 'Synced'), ('queued', 'Queued'), ('processing', 'Processing')], default='queued', max_length=16)),
                ('size_mb', models.PositiveIntegerField()),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('has_public_link', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='main.account')),
            ],
        ),
    ]
