# Generated by Django 5.0.6 on 2026-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_upload_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='size_gb',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Calculated size in gigabytes for quick status summaries.', max_digits=12),
        ),
    ]
