# Generated by Django 5.0.6 on 2026-03-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_upload_size_gb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='size_gb',
        ),
    ]
